### PR TITLE
feat(templates): consolidation

### PR DESCRIPTION
**Pull request by PaleBluDot**
This PR is strickly only for the consolidation of email templates between national and affiliates. 

The first step was to create a dataLoader.html test to test a base template in Sailthru before I updated our current templates. 

There will be a total of 4 templates: 
1. Banner
2. Event
3. Letter (renamed from standard)
4. Sidebox

### CODE REVIEW

**Comment by PaleBluDot** [comment]
So far, only the banner templates have been tested. We still need to test and update the components for the sidebox and event. The letter template should be squared away already.

**Comment by PaleBluDot** [comment]
## How to review

1. Clone the repo `git clone https://github.com/aclu-national/email-builder.git`
2. Move into the directory with `cd email-builder`
3. Change the branch for the PR `git checkout pavel/consolidation`
4. Install all packages with `npm install`
5. Build the templates with `npm run build`
6. Go into the `dist/templates/base` for a built templates to test
7. Head over to [**Sailthru**](https://my.sailthru.com/#rev/today) and changed to the `ACLU-Dev` environment.
8. In the campaigns section, find the campaign `24XXXX NAT GradeAD Template Test`.
9. Choose `CAN Test` for the target Audience.
10. When selecting a template, please use `Data Loader Test`.
11. Copy the code from the `dist/templates/base` files. Paste each file into Sailthru and inspect that all output is correct.
12. Once you tested you final templates, update the campaign name to check the information updates. Instead of the current campaign name `24XXXX NAT GradeAD Template Test`, update `NAT` to `AK`. This is what it should look like `2403XX NAT GradeAD Template Test`.
13. If everything looks good, you can finally approve the PR changes.

**Review by barsinister — COMMENTED** [review]
Everything checks out

**Review by barsinister — APPROVED** [review]

**Pull request merged**
